### ISSUE TITLE
Multiple project support

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4439]
## Useful links

- [Forum feature discussion](https://forum.getodk.org/t/server-url-shown-on-home-screen-multiple-servers-switch-with-colour-change/23340)
- [Figma prototype](https://www.figma.com/file/nDsMAYQDIflyl7rznEhwnN/ODK-Collect-Profiles-v1.31?node-id=0%3A1)
- [Miro architecture](https://miro.com/app/board/o9J_lTbU3Jw=/)

### During regression testing

- [x] #4605
- [x] #4438
- [x] #4576
- [x] https://github.com/getodk/collect/issues/4678
- [x] Look at project settings dialog size for longer project lists

## Done

<details><summary>Click to expand</summary>

### Preparation ☑️
- [x] Find whiteboard tool
- [x] Discuss technical approach and architecture ([Miro](https://miro.com/app/board/o9J_lTbU3Jw=/))
- [x] Stop using unscoped storage (#4435)
- [x] Remove legacy settings import (#4440)
- [x] Make sure `PreferencesProvider` is always used to grab preferences (#4452)
- [x] Switch to using `PreferencesProvider` in `PreferenceFragment` (#4461)
- [x] Introduce current project concept for preferences (#4467)
- [x] Replace usages of Daos with Repositories (#4454)
- [x] Make it so Content Provider is implemented using Repository (#4453)

### Settings UI changes ☑️
- [x] Move settings buttons to new dialog (#4419)
- [x] Move "About" button (#4460)
- [x] Remove Main Menu options menu (#4486)

### Projects CRUD ☑️
- [x] Add "Add project" button (#4420)
- [x] Add icons to projects (#4422)
- [x] Add color to projects (#4492)
- [x] Add ability to select current project (#4497)
- [x] Tweak project form UI (#4506)
- [x] Extract `projects` module
- [x] Projects persist between runs of the app (#4502)
- [x] Add first launch experience (#4498)
- [x] Add upgrade path (#4418)
- [x] Add project icon to main menu (#4423) 
- [x] Add edit screen for projects (#4429)
- [x] Add delete project button (#4424)
- [x] Add server details to project form (#4428)

### Switching between projects ☑️
- [x] Allow switching between projects (#4417)
- [x] Make background jobs work (#4430) 
- [x] Make sure settings migrations work for this version (#4604)

### Project creation ☑️
- [x] Add QR code import for project (#4426)
- [x] Make QR code default way to create project (#4427)
- [x] Add import/export of project details via QR (#4582)
- [x] Refine project color feature (#4493)
- [x] Generate project details for existing project (#4579)
- [x] Polish first launch dialog (#4531)

### Post beta ☑️
- [x] #4654
- [x] #4425
- [x] #4575
- [x] #4640
- [x] #4647
- [x] #4462
- [x] Clean up project directories when project is deleted
- [x] #4577
- [x] #4649
- [x] #4634
- [x] #4644
- [x] #4632
- [x] #4641
- [x] Auto focus on "URL" when adding project manually
- [x] #4584
- [x] Remove existing behavior that saves server URLs for autocompletion in settings
- [x] #4626
- [x] #4578
- [x] #4606
- [x] #4474
- [x] Make it so sync progress bar and errors only show for the current project

</details>

**Comment by seadowg** [comment]
We've now merged the key changes we wanted to make to the way that blank and filled forms are stored (#4453), so it's a good time to pull @kkrawczyk123 and @mmarciniak90 in for a QA pass on master. @lognaturel and I discussed some areas of the app we think should get tested a little while ago:

* Form download (server and gdrive)
* Form open (blank and update)
* Saving forms (in-form, at end, finalize, encrypt)
* Form state (finalized, encrypted, deleted)
* Submission map
* Changing language in form
* Deletion (forms and instances)
* External apps (@grzesiek2010's Collect Tester app)

We probably don't need to test anything about around form entry as that should have stayed the same. We also don't think it makes sense to dive into settings or the new projects flows right now. I'll let @grzesiek2010 add to this if he has other ideas around what to test.

**Comment by grzesiek2010** [comment]
It's difficult to come up with some good advice here. 
I would maybe add checking if the lists of forms/instances work as before sorting/filtering/selecting.

Everything that is related to forms/instances databases might be affected. What @seadowg mentioned are great points but @mmarciniak90 @kkrawczyk123 do not hesitate to be curious and flexible checking other cases that come to your mind.

It's also worth mentioning that some functions like syncing instances in list activities might be intentionally removed/turned on for now (we are going to fix it later). 
Of course the functionality to add/switch projects is not ready yet so please use that dialog just to open settings.
@seadowg anything else here?

**Comment by mmarciniak90** [comment]
@seadowg, successfully sent submission does not disappear from `Send Finalized Form` list. You need to leave the view.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/114710767-63999c80-9d2e-11eb-930c-ab73980d1951.gif)

Submission state is not updated on `Send Finalized Form` list

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/3907554/114718455-49fc5300-9d36-11eb-8331-cfa26bba063d.gif)

Deleted forms are also visible on `Delete Saved Form` list.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/114712346-48c82780-9d30-11eb-8aa0-d1e44f01b5b7.gif)

**Comment by seadowg** [comment]
@mmarciniak90 great finds. It looks like there are some general problems with form lists updating when something changes. Some of these problems show up a gap in our automated tests so plugging that will be helpful for the future. I'm thinking we should file these problems as one bug as they all they seem related?

**Comment by seadowg** [comment]
@mmarciniak90 thanks for creating the issue. Let me know if there are any other problems. I'll start working on fixes on Monday probably.

**Comment by mmarciniak90** [comment]
@seadowg I noticed an issue with auto-send then I use `Fallback submission URL`.
My first thought was that #4513 is the cause but I'm not able to reproduce it on the released version.
Could you take a look?

1. Set Google Drive as a server and add `Fallback submission URL`
2. Select `Auto send` (`Delete after send` is optional but I usually select this option)
3. Download form, finalize it
4. Submission should be sent to the Fallback submission URL automatically but it's visible on the device and you need to send it manually

The issue is not visible when Google Sheet URL is added directly to XML.

---
Another unexpected behavior:

1. Fresh installation of Collect and Collect Tester app are available on device
2. Open Collect Tester
3. Go to `Submit Instance` and put a random number 
4. `Sending form` dialog is visible and the problem with missing submission is not recognized

| v1.30.1| master|
|---|---|
|![Screenshot_20210419-154854](https://user-images.githubusercontent.com/3907554/115248151-bbb61180-a127-11eb-95bd-3d37afb73995.png)|![image](https://user-images.githubusercontent.com/3907554/115248172-c07ac580-a127-11eb-9a2d-8891d4cc54fb.jpg)|

**Comment by seadowg** [comment]
@mmarciniak90 these both look like regressions to me. Could you create issues for them (with the regression tag) please?

**Comment by lognaturel** [comment]
I'm not seeing adding username if it is set and server domain to the project listing. E.g. "collector / banadir.com" below:
<img width="431" alt="Screen Shot 2021-05-13 at 10 00 02 PM" src="https://user-images.githubusercontent.com/967540/118223690-b30adf80-b436-11eb-96a2-c00df13a164a.png">

I may have missed it! If not, I can add it to the polish section.

**Comment by seadowg** [comment]
@lognaturel hmm you're right it's not explicitly mentioned anywhere. I'll add it to the acceptance in https://github.com/getodk/collect/issues/4428 (let me know if you think what I add is enough) as it feels like it'd be nice to do at the same time as adding them into the form. Happy to break it out again if it feels like too much work at the time.

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 we (myself and @grzesiek2010 prompted by @lognaturel) were chatting about parts of the app that it would be possible to do a pass on at the moment. Our thinking is that it would be useful to have a pass on the following areas:

* Upgrading from an existing version of the app - you should have a single project without all your settings, forms etc
* Adding projects manually
* Switching between projects (forms, instances and settings should all work as expected for project)
* Weird(er) forms: external selects, encryption etc

One thing to keep in mind is that "Form update" settings won't function as expected as previously downloaded and match exactly modes haven't been updated to work with projects. Likewise for "Auto send". I'd avoid configurations that have any of those things turned on as it will definitely cause confusion.

I think it'd be best to wait for #4587 to merge before testing `master` as that fixes problems with configuring a project via a QR code (from Admin settings) which would definitely make testing more awkward. 

Happy hunting! @grzesiek2010, @lognaturel please chip in if you think there are other things we should test.

**Comment by mmarciniak90** [comment]
> Upgrading from an existing version of the app - you should have a single project without all your settings, forms etc

I want to clarify the current behavior with the latest changes.
I generated this QR code on v1.30.1. After the upgrade, all changes from Admin Settings are missed, changes from General Settings are OK. The most noticeable for me is the missing password to Admin Settings.
![collect-settings](https://user-images.githubusercontent.com/3907554/121373274-3ab51280-c93f-11eb-8a4e-8bca75fbf7e7.png)

I know that work on this revolution is still in progress so I marked all noticed smaller or bigger issues.

- upgrade from 1.30.1 to master (8 June)
   - ⚠️  mentioned issue with Admin Settings 
   - used the same data (forms, submissions, layers), settings as in the case with migration
- fresh installation - first screen
   - ⚠️I'm not able to scroll when I changed device orientation to horizontal
   - used demo project
   - add custom project
   - ⚠️ there is no validation on URL, I  was able to create new project with only one letter in URL field
- created 5 different projects: Demo, Aggregate, Central, Google Drive, Kobo, ONA
   - ⚠️  if many projects are available, area to scroll on project list is not the most pleasant to use
   - ⚠️ when I added 4th and next project I didn't see it because it was added at the end of the list - it could be confusing, user may not be sure that adding was finished with success
- switching between projects 
   - loading correct forms and submissions 
- bunch of different forms
- changed project details in Admin settings
   ⚠️  crash when I manipulated project color - I know that Grzegorz is working on new dialog with palette
- used different settings on each project
   - light/dark mode
   - languages

**Comment by seadowg** [comment]
@mmarciniak90 Thanks for these! I'll have a look through these with @lognaturel later and triage into issues. I actually put a note into the backlog yesterday to check on the settings migrations that happen on upgrade, so I'm not surprised that ended up being a problem!

**Comment by kkrawczyk123** [comment]
I want to point out few things, probably some of them has been already considered:
- When adding a project there is no validation on valid URL. I can input anything. It is also visible when scan qr code with settings you are able to import an invalid URL and it is set as a server in a new project. 

- Local server is displayed without a port on the select project modal. 1st number is added by default what is also a little weird but I don’t have any alternative ideas for that, see:
![Screenshot (Jun 2, 2021 11_42_45 AM)](https://user-images.githubusercontent.com/33342488/121523747-d786b700-c9f6-11eb-8ba6-b717b6f8eb16.png)


- When scan QR code with credentials through admin setting, URL is updated on projects modal but project name is not.  You can have a different URL in a project name and in URL below what looks weird and it's confusing. Maybe URL should not be set as project name as default? or it should be updated each time?? The same thing is visible when you reset settings for the project, old URL is visible and project name and demo server as URL:
![Screenshot (11_46AM, Jun 02, 2021)](https://user-images.githubusercontent.com/33342488/121524092-3d733e80-c9f7-11eb-86cb-6258189cf439.png)


- When scanned Central’s testing instance qr code on projects dialog there is: test.getodk.cloud but project number information is also valuable for users so maybe we should consider correcting that. Especially when add a few Central’s projects as separate projects in Collect it looks like: 
![Screenshot_20210610-131028_ODK Collect](https://user-images.githubusercontent.com/33342488/121524182-55e35900-c9f7-11eb-87c2-1d56de3feb35.jpg)


Maybe there should be also some indicator about testing draft form on Central. 

- When add a project on the starting dialog manually or using QR code user doesn’t have a demo project added what might be confusing especially for new users as there won’t be a server to try things.

- I have also noticed one more issue connected to changing colors in projects but let’s wait for the new color picker as it won’t be probably visible after adding it.  

- When create a new project there is no way to select Google Drive type of project/Google account as URL is required. I input anything as URL and then edit in general settings. Project name, icon are empty there is no indicator to differentiate drive project on add/switch project dialog. If validation for valid URLs will be added users will have to add URL and then edit to Google Drive in Settings - old url will be visible on dialog then.

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 ok so here's what we're doing to deal with all this:

* There is already a note around the admin settings problem in the backlog (I'll write up an issue late) and we'll need to deal with that pre beta.
* We've added notes to #4531 around problems that were found on the first launch screen
* We'll do a visual tweaks pass probably after beta to address a large set of the visual problem you encountered
* What exactly we should do with longer project lists is something we need to think about, but ultimately we want to see how many projects people actually end up with to make a lot of those decisions.
* We've got an issue (#4575) to deal with Google Drive and projects (post beta release)
* Central will be adding project name as part of its QR code so that we don't run into the duplicated project name problem
* Some things like URL validation and showing the port as part of the URL on the project we probably won't look at fixing unless we see feedback from users that it's causing them frustration.

Thanks again! We'll hopefully be ready to do another pass with the full creation flow and background jobs in the next week or so.

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 I think we're now able to do a more full sweep of the new projects features. This includes form update modes, auto send and upgrades from older versions which I think are definitely some of the riskiest/scariest areas. I've tagged you both on an issue around investigating upgrades on devices with a lot of forms/instances as well.
